spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: 'jdbc:h2:mem:test_mem'
  kafka:
    listener:
      ack-mode: record
    consumer:
      enable-auto-commit: false
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value.default.type: com.pszymczyk.commands.OrderCommand
      group-id: spring-kafka-playground-v8
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
      path: /h2-console