spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:h2:file:./h2-db/db;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;'
  kafka:
    listener:
      ack-mode: record
    consumer:
      enable-auto-commit: false
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: com.pszymczyk.commands
            value.default.type: com.pszymczyk.commands.OrderCommand
      group-id: spring-kafka-playground-v1
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
      path: /h2-console